# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-fEsCHBcTwKG5Gbaq6BgfZGAJWNvYks
"""

# api_mnist.py
# FastAPI for MNIST CNN (PyTorch)

from fastapi import FastAPI, File, UploadFile
import torch
import torch.nn as nn
from torchvision import transforms
from PIL import Image
import io
from fastapi.middleware.cors import CORSMiddleware
app=FastAPI(title="MNIST CNN API")
#Allow frontend access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"]
    allow_credentials=True,
    allow_methods=["*"]
    allow_headers=["*"],
)
DEVICE=torch.device("cuda",if torch.cuda.is_available() else "cpu")

# 1. Define the same CNN model architecture
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()

        self.conv1 = nn.Conv2d(1, 32, kernel_size=3)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3)

        self.fc1 = nn.Linear(64 * 5 * 5, 128)
        self.fc2 = nn.Linear(128, 10)

        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.pool(self.relu(self.conv1(x)))
        x = self.pool(self.relu(self.conv2(x)))
        x = x.view(-1, 64 * 5 * 5)
        x = self.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# 2. Load model and weights
model = CNN()
model.load_state_dict(torch.load("cnn_mnist_weights.pth", map_location=torch.device('cpu')))
model.eval()

# 3. Define image transformation
transform = transforms.Compose([
    transforms.Grayscale(),       # Ensure grayscale
    transforms.Resize((28, 28)),  # Resize to MNIST size
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

# 4. Create FastAPI app
app = FastAPI()

@app.get("/")
def home():
    return {"message": "MNIST CNN API is running!"}

# 5. Prediction endpoint
@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    # Read image
    image_bytes = await file.read()
    image = Image.open(io.BytesIO(image_bytes))

    # Preprocess image
    image = transform(image).unsqueeze(0)  # Add batch dimension

    # Predict
    with torch.no_grad():
        outputs = model(image)
        _, predicted = torch.max(outputs, 1)

    return {"predicted_digit": int(predicted.item())}